# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: authlogic_radius_ldap 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "authlogic_radius_ldap".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Brad Langhorst".freeze]
  s.date = "2024-04-02"
  s.description = "This is a simple gem to allow authentication against a RADIUS or LDAP server.\n".freeze
  s.email = "langhorst@neb.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/authlogic_radius.rb",
    "lib/authlogic_radius_ldap/acts_as_authentic.rb",
    "lib/authlogic_radius_ldap/session.rb",
    "lib/authlogic_radius_ldap/version.rb"
  ]
  s.homepage = "http://github.com/bwlang/authlogic_radius".freeze
  s.rubygems_version = "3.1.6".freeze
  s.summary = "Extension of the Authlogic library adding RADIUS and LDAP support.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<authlogic>.freeze, [">= 2.0"])
    s.add_runtime_dependency(%q<radiustar>.freeze, [">= 0.0.3"])
  else
    s.add_dependency(%q<authlogic>.freeze, [">= 2.0"])
    s.add_dependency(%q<radiustar>.freeze, [">= 0.0.3"])
  end
end

